#!/bin/bash
printf "\e[9;1t"
tmux new -d '~/Documents/GitHub/Uno/uno 2 "gamer 1" "game room"'
sleep 0.05
tmux splitw '~/Documents/GitHub/Uno/uno 1 "gamer 2" "game room"'
sleep 0.05
tmux splitw '~/Documents/GitHub/Uno/uno 1 "gamer 3" "game room"'
sleep 0.05
tmux splitw '~/Documents/GitHub/Uno/uno 1 "gamer 4" "game room"' ';' \
selectl tiled ';' \
attach
printf "\e[9;0t"