#!/bin/bash
printf "\e[9;1t"
tmux new -d '~/Documents/GitHub/Uno/uno' ';' \
splitw '~/Documents/GitHub/Uno/uno' ';' \
splitw '~/Documents/GitHub/Uno/uno' ';' \
splitw '~/Documents/GitHub/Uno/uno' ';' \
selectl tiled ';' \
send -t 0 "2" "Enter" "gamer 1" "Enter" "game room" "Enter"
sleep 0.05
tmux send -t 1 "1" "Enter" "1" "Enter" "gamer 2" "Enter"
sleep 0.05
tmux send -t 2 "1" "Enter" "1" "Enter" "gamer 3" "Enter"
sleep 0.05
tmux send -t 3 "1" "Enter" "1" "Enter" "gamer 4" "Enter" ';' \
attach
printf "\e[9;0t"